# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import model_serving_pb2 as model__serving__pb2


class ModelStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Predict = channel.unary_unary(
        '/Model/Predict',
        request_serializer=model__serving__pb2.Input.SerializeToString,
        response_deserializer=model__serving__pb2.Output.FromString,
        )


class ModelServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Predict(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ModelServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Predict': grpc.unary_unary_rpc_method_handler(
          servicer.Predict,
          request_deserializer=model__serving__pb2.Input.FromString,
          response_serializer=model__serving__pb2.Output.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Model', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
